export const elements = {
  input: getElement<HTMLInputElement>("stock-name"),
  primaryAction: getElement<HTMLButtonElement>("primary-action"),
  taskStatus: getElement<HTMLElement>("task-status"),
  codexStatus: getElement<HTMLElement>("codex-status"),
  redetectCodex: getElement<HTMLButtonElement>("redetect-codex"),
  refreshHistory: getElement<HTMLButtonElement>("refresh-history"),
  historyList: getElement<HTMLElement>("history-list"),
  reportDirectory: getElement<HTMLElement>("report-directory"),
  configureDirectory: getElement<HTMLButtonElement>("configure-directory"),
  openPdf: getElement<HTMLButtonElement>("open-pdf"),
  retryPdf: getElement<HTMLButtonElement>("retry-pdf"),
  reportPanel: getElement<HTMLElement>("report-panel"),
  outputPanel: getElement<HTMLElement>("output-panel"),
  liveOutputScroll: getElement<HTMLElement>("live-output-scroll"),
  liveOutput: getElement<HTMLElement>("live-output"),
  workingIndicator: getElement<HTMLElement>("working-indicator"),
  workingElapsed: getElement<HTMLElement>("working-elapsed"),
  specPanel: getElement<HTMLElement>("spec-panel"),
  researchSpec: getElement<HTMLTextAreaElement>("research-spec"),
  saveSpec: getElement<HTMLButtonElement>("save-spec"),
  resetSpec: getElement<HTMLButtonElement>("reset-spec"),
  specStatus: getElement<HTMLElement>("spec-status"),
  researchSidebarContent: getElement<HTMLElement>("research-sidebar-content"),
  researchWorkspace: getElement<HTMLElement>("research-workspace"),
  watchWorkspace: getElement<HTMLElement>("watch-workspace"),
  watchStatus: getElement<HTMLElement>("watch-status"),
  watchWorkspaceTabs: getElement<HTMLElement>("watch-workspace-tabs"),
  addWatchWorkspace: getElement<HTMLButtonElement>("add-watch-workspace"),
  watchTradingDate: getElement<HTMLSelectElement>("watch-trading-date"),
  watchMarketError: getElement<HTMLElement>("watch-market-error"),
  refreshWatchQuotes: getElement<HTMLButtonElement>("refresh-watch-quotes"),
  refreshWatchNews: getElement<HTMLButtonElement>("refresh-watch-news"),
  showWatchNewsDebug: getElement<HTMLButtonElement>("show-watch-news-debug"),
  exportWatchData: getElement<HTMLButtonElement>("export-watch-data"),
  importWatchData: getElement<HTMLButtonElement>("import-watch-data"),
  watchPanel: getElement<HTMLElement>("watch-panel"),
  watchTree: getElement<HTMLElement>("watch-tree"),
  watchContextMenu: getElement<HTMLElement>("watch-context-menu"),
  watchNewsTooltip: getElement<HTMLElement>("watch-news-tooltip"),
  watchNewsHistoryPanel: getElement<HTMLElement>("watch-news-history-panel"),
  watchNewsHistoryHeader: getElement<HTMLElement>("watch-news-history-header"),
  watchNewsHistoryTitle: getElement<HTMLElement>("watch-news-history-title"),
  watchNewsHistoryContent: getElement<HTMLElement>("watch-news-history-content"),
  closeWatchNewsHistory: getElement<HTMLButtonElement>("close-watch-news-history"),
  watchNewsDebugPanel: getElement<HTMLElement>("watch-news-debug-panel"),
  watchNewsDebugTitle: getElement<HTMLElement>("watch-news-debug-title"),
  watchNewsDebugContent: getElement<HTMLElement>("watch-news-debug-content"),
  closeWatchNewsDebug: getElement<HTMLButtonElement>("close-watch-news-debug"),
  watchNodeDialog: getElement<HTMLDialogElement>("watch-node-dialog"),
  watchNodeForm: getElement<HTMLFormElement>("watch-node-form"),
  watchNodeDialogTitle: getElement<HTMLElement>("watch-node-dialog-title"),
  watchNodeType: getElement<HTMLSelectElement>("watch-node-type"),
  watchNodeName: getElement<HTMLInputElement>("watch-node-name"),
  searchWatchStock: getElement<HTMLButtonElement>("search-watch-stock"),
  watchStockResults: getElement<HTMLElement>("watch-stock-results"),
  watchNodeSecidLabel: getElement<HTMLElement>("watch-node-secid-label"),
  watchNodeSecid: getElement<HTMLInputElement>("watch-node-secid"),
  watchNodeIndustryPositionLabel: getElement<HTMLElement>("watch-node-industry-position-label"),
  watchNodeIndustryPosition: getElement<HTMLSelectElement>("watch-node-industry-position"),
  watchNodeHoldingLabel: getElement<HTMLElement>("watch-node-holding-label"),
  watchNodeHolding: getElement<HTMLSelectElement>("watch-node-holding"),
  watchNodeError: getElement<HTMLElement>("watch-node-error"),
  cancelWatchNode: getElement<HTMLButtonElement>("cancel-watch-node"),
  marketProviderDialog: getElement<HTMLDialogElement>("market-provider-dialog"),
  marketProviderForm: getElement<HTMLFormElement>("market-provider-form"),
  marketProviderSelect: getElement<HTMLSelectElement>("market-provider-select"),
  marketProviderStatus: getElement<HTMLElement>("market-provider-status"),
  cancelMarketProvider: getElement<HTMLButtonElement>("cancel-market-provider"),
  modelProviderDialog: getElement<HTMLDialogElement>("model-provider-dialog"),
  modelProviderForm: getElement<HTMLFormElement>("model-provider-form"),
  modelProviderSelect: getElement<HTMLSelectElement>("model-provider-select"),
  codexModelSettings: getElement<HTMLElement>("codex-model-settings"),
  codexModelStatus: getElement<HTMLElement>("codex-model-status"),
  redetectModelCodex: getElement<HTMLButtonElement>("redetect-model-codex"),
  deepSeekModelSettings: getElement<HTMLElement>("deepseek-model-settings"),
  deepSeekBaseUrl: getElement<HTMLInputElement>("deepseek-base-url"),
  deepSeekModel: getElement<HTMLSelectElement>("deepseek-model"),
  deepSeekCustomModelSettings: getElement<HTMLElement>("deepseek-custom-model-settings"),
  deepSeekCustomModel: getElement<HTMLInputElement>("deepseek-custom-model"),
  deepSeekReasoningEffort: getElement<HTMLSelectElement>("deepseek-reasoning-effort"),
  deepSeekApiKey: getElement<HTMLInputElement>("deepseek-api-key"),
  deepSeekApiKeyStatus: getElement<HTMLElement>("deepseek-api-key-status"),
  clearDeepSeekApiKey: getElement<HTMLButtonElement>("clear-deepseek-api-key"),
  tavilyApiKey: getElement<HTMLInputElement>("tavily-api-key"),
  tavilyApiKeyStatus: getElement<HTMLElement>("tavily-api-key-status"),
  clearTavilyApiKey: getElement<HTMLButtonElement>("clear-tavily-api-key"),
  modelProviderStatus: getElement<HTMLElement>("model-provider-status"),
  cancelModelProvider: getElement<HTMLButtonElement>("cancel-model-provider"),
  watchNewsSettingsDialog: getElement<HTMLDialogElement>("watch-news-settings-dialog"),
  watchNewsSettingsForm: getElement<HTMLFormElement>("watch-news-settings-form"),
  watchNewsIntervalHours: getElement<HTMLInputElement>("watch-news-interval-hours"),
  watchNewsSettingsStatus: getElement<HTMLElement>("watch-news-settings-status"),
  cancelWatchNewsSettings: getElement<HTMLButtonElement>("cancel-watch-news-settings")
};

export type RendererElements = typeof elements;

function getElement<T extends HTMLElement>(id: string): T {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Missing element: ${id}`);
  }
  return element as T;
}
